---
title: "Sensitivity Analyses for Overdose Spikes"
authors: "Daniel Otero-Leon and Hannah Lee"
date: "6/7/2024"
output: html_document

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = '.')

library(dplyr)
library(lubridate)
library(progress)
library(tidyr)

setwd("/Users/Hannah/Documents/R/Mass-Vital-Statistics")
```


Modified threshold algorithm for sensitivity analysis (adds new outputs)
```{r}
ThresholdingAlgo2 <- function(y,lag,threshold,influence) {
  signals <- rep(0,length(y))
  filteredY <- y[1:lag]
  avgFilter <- NULL
  stdFilter <- NULL
  spikes<-rep(0,length(y))
  dips<-rep(0,length(y))
  avgFilter[lag] <- mean(y[1:lag], na.rm=TRUE)
  stdFilter[lag] <- sd(y[1:lag], na.rm=TRUE)
  for (i in (lag+1):length(y)){
    if (abs(y[i]-avgFilter[i-1]) > threshold*stdFilter[i-1]) {
      if (y[i] > avgFilter[i-1]) {
        signals[i] <- 1
        spikes[i]<-y[i]
        dips[i]<-0
        } 
      else {
        signals[i] <- -1
        dips[i]<-y[i]
        spikes[i]<-0
      }
      filteredY[i] <- influence*y[i]+(1-influence)*filteredY[i-1]
    } else {
      signals[i] <- 0
      spikes[i]<-0
      dips[i]<-0
      filteredY[i] <- y[i]
    }
    avgFilter[i] <- mean(filteredY[(i-lag+1):i], na.rm=TRUE)
    stdFilter[i] <- sd(filteredY[(i-lag+1):i], na.rm=TRUE)
  }
  return(list("signals"=signals,"avgFilter"=avgFilter,"stdFilter"=stdFilter,"spikes"=spikes,"dips"=dips))
}

#Parameters for the sensitivity analysis. Change the array accordingly
lag<-c(7,15,30,60,90,120,150,180)
threshold <- c(2.0,2.1,2.2,2.3,2.4,2.5,2.6,2.7,2.8,2.9,3)
influence<-c(0.3)

```



Sensitivity analysis by year
```{r}

# Sensitivity analysis function
sens_analysis <- function(geographical_data, lag, threshold, influence) {
  y <- geographical_data$Total_Overdose_Deaths
  date <- geographical_data$DOD_4_FD
  years <- as.integer(format(date, "%Y"))
  
  theResult <- NULL
  
  pb <- progress_bar$new(format = " running [:bar] :percent eta: :eta", total = length(lag), clear = FALSE, width = 60)
  
  for (i in 1:length(lag)) {
    pb$tick()
    for (j in 1:length(threshold)) {
      for (k in 1:length(influence)) {
        # Run the spike detection algorithm
        result <- ThresholdingAlgo2(y, lag[i], threshold[j], influence[k])
        
        # Prepare the results in a dataframe
        df <- data.frame(
          date = date,
          year = years,
          y = y,
          avgFilter = result$avgFilter,
          upperThreshold = result$avgFilter + threshold[j] * result$stdFilter,
          signals = result$signals,
          spikes = result$spikes,
          dips = result$dips
        )
        
        # Add the difference between deaths and the moving average
        df$y_minus_avgFilter <- df$y - df$avgFilter
        
        df_modified <- df %>%
          group_by(year) %>%
          summarise(
            total_days = n(),  # Total days in the year
            spike_days = sum(signals == 1),  # Days identified as spikes
            total_deaths = sum(y),  # Total deaths in the year
            deaths_in_spikes = sum(spikes),  # Total deaths during spikes
            avg_diff_in_spikes = mean(y_minus_avgFilter[signals == 1], na.rm = TRUE)  # Average difference for spike days
          ) %>%
          mutate(
            perc_spike_days = (spike_days / total_days) * 100,  # Percentage of days identified as spikes
            perc_spike_deaths = (deaths_in_spikes / total_deaths) * 100  # Percentage of deaths in spikes
          )
        
        # Add the parameters used
        df_modified$lag <- lag[i]
        df_modified$threshold <- threshold[j]
        df_modified$influence <- influence[k]
        
        # Combine results
        if (is.null(theResult)) {
          theResult <- df_modified
        } else {
          theResult <- bind_rows(theResult, df_modified)
        }
      }
    }
  }
  
  return(theResult)
}

# Run the sensitivity analysis
sensAnalysis <- sens_analysis(daily_overdose_deaths_ma, lag, threshold, influence)

sensAnalysis <- sensAnalysis %>%
  filter(year >= 2017 & year <= 2023) %>%
  mutate_if(is.numeric, round, 2)
```

Sensitivity analysis for all years
```{r}
# Sensitivity analysis function
sens_analysis_all_years <- function(geographical_data, lag, threshold, influence) {
  y <- geographical_data$Total_Overdose_Deaths
  date <- geographical_data$DOD_4_FD
  years <- as.integer(format(date, "%Y"))
  
  theResult <- NULL
  
  pb <- progress_bar$new(format = " running [:bar] :percent eta: :eta", total = length(lag), clear = FALSE, width = 60)
  
  for (i in 1:length(lag)) {
    pb$tick()
    for (j in 1:length(threshold)) {
      for (k in 1:length(influence)) {
        # Run the spike detection algorithm
        result <- ThresholdingAlgo2(y, lag[i], threshold[j], influence[k])
        
        # Prepare the results in a dataframe
        df <- data.frame(
          date = date,
          year = years,
          y = y,
          avgFilter = result$avgFilter,
          upperThreshold = result$avgFilter + threshold[j] * result$stdFilter,
          signals = result$signals,
          spikes = result$spikes,
          dips = result$dips
        )
        
        # Add the difference between deaths and the moving average
        df$y_minus_avgFilter <- df$y - df$avgFilter
        
        df_modified <- df %>%
          summarise(
            total_days = n(),  # Total days in the data
            spike_days = sum(signals == 1),  # Days identified as spikes
            total_deaths = sum(y),  # Total deaths in the data
            deaths_in_spikes = sum(spikes),  # Total deaths during spikes
            avg_diff_in_spikes = mean(y_minus_avgFilter[signals == 1], na.rm = TRUE)  # Average difference for spike days
          ) %>%
          mutate(
            perc_spike_days = (spike_days / total_days),  # Percentage of days identified as spikes
            perc_spike_deaths = (deaths_in_spikes / total_deaths)  # Percentage of deaths in spikes
          )
        
        # Add the parameters used
        df_modified$lag <- lag[i]
        df_modified$threshold <- threshold[j]
        df_modified$influence <- influence[k]
        
        # Combine results
        if (is.null(theResult)) {
          theResult <- df_modified
        } else {
          theResult <- bind_rows(theResult, df_modified)
        }
      }
    }
  }
  
  return(theResult)
}

daily_overdose_deaths_ma_filtered <- daily_overdose_deaths_ma %>%
  filter(YOD >= 2017 & YOD <= 2023)

# Run the sensitivity analysis
sensAnalysis_all_years <- sens_analysis_all_years(daily_overdose_deaths_ma_filtered, lag, threshold, influence)

# Reformat table
sensAnalysis_all_years_days <- sensAnalysis_all_years %>%
  select(lag, threshold, perc_spike_days) %>%
  pivot_wider(names_from = lag, values_from = perc_spike_days)
sensAnalysis_all_years_deaths <- sensAnalysis_all_years %>%
  select(lag, threshold, perc_spike_deaths) %>%
  pivot_wider(names_from = lag, values_from = perc_spike_deaths)
```

```{r}
sens_analysis_year_days <- function(geographical_data, lag, threshold, influence)
{
  
  y <- geographical_data$Total_Overdose_Deaths
  
  theResult<-0
    pb <- progress_bar$new(format = " running [:bar] :percent eta: :eta",total = length(lag), clear = FALSE, width= 60)
  for(i in 1:length(lag))
  {
    pb$tick()
    for(j in 1:length(threshold))
    {
      for( k in 1:length(influence))
      {
        result <- ThresholdingAlgo2(y,lag[i],threshold[j],influence[k])
        df <- data.frame(date = geographical_data$DOD_4_FD, 
                         y = y, 
                         avgFilter = result$avgFilter, 
                         stdFilter = result$stdFilter,
                         upperThreshold = result$avgFilter + threshold[j] * result$stdFilter, 
                         signals = result$signals,
                         spikes=result$spikes,
                         dips=result$dips,
                         YOD = geographical_data$YOD)
        df$year <- year(df$date)
        df_modified <- df
        df_modified$modified_y <- ifelse(df$signals == 0, 0, df$y)
        df_modified$y_minus_avgFilter_or_zero <- ifelse(df$signals == 0, 0, df$y - df$avgFilter)
        df_modified$lag<-lag[i]
        df_modified$threshold<-threshold[j]
        df_modified$influence<-influence[k]
        df_modified$percSpike<-ifelse(df_modified$signals==1,df_modified$y_minus_avgFilter_or_zero/df_modified$avgFilter,0)
        df_modified<-df_modified[df_modified$year>=2017 & df_modified$year<=2022,]
        if(i==1 & j==1 & k==1)
        {
          theResult<-df_modified
        }
        else
        {
          theResult<-rbind(theResult,df_modified)
        }   
      }
    }
    Sys.sleep(1 / 100)
  }
  
   return(theResult)
  
}
sensAnalysisYearDays<-sens_analysis_year_days(daily_overdose_deaths_ma, lag, threshold, influence)
```

