---
title: "Detected Spikes Visualization"
authors: "Hannah Lee and Daniel Otero-Leon"
date: "6/7/2024"
output: html_document

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = '.')

library(dplyr)
library(ggplot2)
library(cowplot)
library(extrafont)

font_import()
setwd("/Users/Hannah/Documents/R/Mass-Vital-Statistics")
```


```{r}
createPlot <- function(data, threshold, lag_days, show_y_axis = TRUE) {
  # Filter the data based on the threshold and specific lag
  theData <- data[data$threshold == threshold & data$lag == lag_days,]

  # In our algorithm, the avgfilter and stdfilter of 'i' corresponds to 'i-1', so for presentation, we must adjust the rows
  theData$avgFilter <- c(NA, theData$avgFilter[1:(nrow(theData) - 1)])
  theData$upperThreshold <- c(NA, theData$upperThreshold[1:(nrow(theData) - 1)])
  theData$spikes <- ifelse(theData$spikes > 0, theData$spikes, NA)
  
  # Filter for specific months and year
  filtered_data <- theData %>%
    filter(year(date) == 2022, month(date) %in% c(11, 12))
  
  # Create the plot
  plot <- ggplot(filtered_data, aes(x = date)) +
    geom_line(aes(y = y, color = 'Observed counts'), size = 0.7) +
    geom_line(aes(y = avgFilter, color = 'Moving average'), size = 0.7) +
    geom_line(aes(y = upperThreshold, color = 'Upper bound'), size = 0.7) +
    geom_point(aes(y = spikes, color = 'Spike'), size = 2) +
    
    # Set theme with consistent font, color, and size
    theme_minimal() +
    theme(
      legend.position = "none",
      axis.title.x = element_text(margin = margin(t = 10, unit = "pt")),
      axis.title.y = element_text(margin = margin(r = 10, unit = "pt")),
      plot.title = element_text(family = "Arial", color = "black", size = 12),  # Optional: bold title
      axis.text.x = element_text(family = "Arial", color = "black", size = 12),  # X-axis text
      axis.text.y = element_text(family = "Arial", color = "black", size = 12),  # Y-axis text
      
    ) +
    scale_color_manual(
      name = "",
      values = c(
        'Observed counts' = "#e4e1e3",
        'Moving average' = "#b5006b",
        'Spike' = "#f6222e",
        'Upper bound' = "#feaf16"
      )
    ) +
    scale_x_date(
      date_labels = "%b %e", 
       expand = expansion(mult = c(0.07, 0.07))  # Adds 5% padding on both sides
  
    ) +
    labs(
      title = paste(lag_days, "-Day lag", sep = ""),
      x = "2022",
      y = ifelse(show_y_axis, "No. of overdose deaths", "")
    ) +
    scale_y_continuous(
      breaks = seq(0, 15, 3),
      limits = c(-0.5, 15),
      expand = c(0, 0)
    )
  
  # Conditionally remove y-axis and y-title
  if (!show_y_axis) {
    plot <- plot +
      theme(
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.title.y = element_blank()
      )
  }

  return(plot)
}

```

```{r}
lags <- c(7, 30, 90)
show_y_axis_settings <- c(TRUE, FALSE, FALSE) # Control display of y-axis for each plot
threshold <- 2  

# Create plots with specific settings (influence will be 0.3 only)
plots <- Map(function(lag, show_y) {
    createPlot(sensAnalysisYearDays, threshold, lag, show_y)
}, lags, show_y_axis_settings)


# Extract the legend from the first plot (requires older version of ggplot)
legend <- get_legend(plots[[1]] + theme(legend.position = "bottom"))

# Combine plots horizontally without the legends
combined_plots <- plot_grid(plotlist = plots, align = 'v', nrow = 1, labels = LETTERS[1:3])

detected_spikes <- plot_grid(combined_plots, legend, ncol = 1, rel_heights = c(1, 0.1))
print(detected_spikes)

ggsave("detected_spikes.jpeg", plot = detected_spikes, width = 10, height = 5, dpi = 1000)
```